import "~/styles/globals.css";

import { api } from "~/utils/api";
import type { ReactElement, ReactNode } from "react";
import { Inter } from "next/font/google";

import { type NextPage } from "next";
import { type AppProps } from "next/app";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

/**
 * Use these types if your component uses a layout
 *
 * See https://nextjs.org/docs/basic-features/layouts
 */
// eslint-disable-next-line
export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
  protected: boolean;
};

/**
 * modify AppProps to include session from tRPC and so that
 *  it can be used with layouts
 */
type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

const MyApp = ({ Component, pageProps }: AppPropsWithLayout) => {
  const getLayout = Component.getLayout ?? ((page) => page);

  const isProtected = Component.protected;

  const page = <Component {...pageProps} />;
  const toRender = isProtected ? (
    <>
      <SignedIn>{page}</SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </>
  ) : (
    page
  );

  return (
    <>
      <Head>
        <title>Icon GiPiTy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${inter.className} flex min-h-screen flex-col`}>
        <ClerkProvider {...pageProps}>{getLayout(toRender)}</ClerkProvider>
      </div>
    </>
  );
};

export default api.withTRPC(MyApp);
