import Head from "next/head";
import { type NextPageWithLayout } from "./_app";
import { SignInButton, SignedOut, useUser } from "@clerk/nextjs";
import MySignOutButton from "~/components/auth/MySignOutButton";
import MySignInButton from "~/components/auth/MySignInButton";
import { IconButton } from "~/components/atoms/IconButton";
import { IconClockFilled } from "@tabler/icons-react";

const Home: NextPageWithLayout = () => {
  const user = useUser();

  console.log("user", user);

  return (
    <>
      <Head>
        <title>Icon GiPiTy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <nav className="flex items-center justify-between px-72 py-12">
          <h1 className="text-3xl font-semibold tracking-tighter dark:text-white">
            Icon GiPiTy
          </h1>
          <MySignOutButton />
          <MySignInButton />
          {/* <IconButton>
            <IconClockFilled size={18} />
          </IconButton> */}
        </nav>
      </main>
    </>
  );
};

Home.protected = false;

export default Home;
